esphome:
  name: climate
  friendly_name: climate

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "s2PJlblzhmpqbFnlyVWlETkwKJPJTLygJOQ4ad+ZOYs="

ota:
  - platform: esphome
    password: "87ae36db2dfd6f86d6a426689cb2d6e3"

wifi:
  ssid: Xiaomi_tracert
  password: "60312131"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Climate Fallback Hotspot"
    password: "Ap60312131"
    
web_server:
  port: 80

uart:
  id: ac_uart_bus
  tx_pin: GPIO05
  rx_pin: GPIO04
  baud_rate: 9600

climate:
  - platform: midea
    name: Midea Climate         # Use a unique name.
    uart_id: ac_uart_bus
    autoconf: false              # Autoconfigure most options.
