esphome:
  name: climate
  friendly_name: climate

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "s2PJlblzhmpqbFnlyVWlETkwKJPJTLygJOQ4ad+ZOYs="

ota:
  - platform: esphome
    password: "87ae36db2dfd6f86d6a426689cb2d6e3"

wifi:
  ssid: Xiaomi_tracert
  password: "60312131"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Climate Fallback Hotspot"
    password: "Ap60312131"
    
web_server:
  port: 80

uart:
  id: ac_uart_bus
  tx_pin: GPIO05
  rx_pin: GPIO04
  baud_rate: 9600

climate:
  - platform: midea
    name: Midea Climate
    uart_id: ac_uart_bus
    period: 2s                 # Увеличим период опроса
    timeout: 3s                # Увеличим таймаут ожидания ответа
    num_attempts: 2            # Уменьшим количество попыток
    autoconf: false            # <-- ГЛАВНОЕ ИЗМЕНЕНИЕ! Отключаем автоопределение
    beeper: false              # Пока отключим и звук, чтобы не мешал
    protocol_version: 2        # Пробуем строго версию 2
    visual:                    
      min_temperature: 17 °C   
      max_temperature: 30 °C   
      temperature_step: 0.5 °C 
    supported_modes:           # Эти режимы будут показаны в интерфейсе
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    supported_swing_modes:     # Опционально, если не будет работать - уберем
      - VERTICAL
    custom_fan_modes:          # Опционально
      - SILENT
      - TURBO
    supported_presets:         
      - ECO
      - BOOST
      - SLEEP
