esphome:
  name: climate_v2
  friendly_name: climate v2

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  #baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "s2PJlblzhmpqbFnlyVWlETkwKJPJTLygJOQ4ad+ZOYs="

ota:
  - platform: esphome
    password: "qwaser42qwaser42qwaser42qwaser42"

wifi:
  ssid: tracertino
  password: "Defaultr123"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Climate Fallback Hotspot"
    password: "Ap60312131"

# Enable Web server.
web_server:
  port: 80

uart:
  id: ac_uart_bus
  tx_pin: GPIO04
  rx_pin: GPIO05
  baud_rate: 9600

climate:
  - platform: midea
    id: midea_climate
    name: Midea Climate A         # Use a unique name.
    uart_id: ac_uart_bus
    

